version: "3.8"

services:
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playground_db
    ports:
      - "5451:5432"

networks:
  default:
    name: local_development_network
