spring:
  datasource:
    url: jdbc:postgresql://localhost:5451/playground_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none
  liquibase:
    enabled: true


